globalVariables(names = c("variable_id",
                          "name",
                          "sample_id",
                          "group",
                          "class",
                          "Domain",
                          "Phylum",
                          "Class",
                          "Order",
                          "Family",
                          "Genus",
                          "Species",
                          "intensity",
                          "label",
                          "log_intensity",
                          "node",
                          "taxa_rank"))